#!/usr/bin/env python3
# Writes Sources/RelayCore/Render/EmojiTable.swift from a gemoji db
# (github/gemoji's emoji.json; oh-my-zsh ships one as plugins/emoji/gemoji_db.json)
# plus the Slack shortcodes gemoji spells differently.
#   python3 -I dev/gen-emoji.py ~/.oh-my-zsh/plugins/emoji/gemoji_db.json
import json, sys, os

SLACK = {
    "thinking_face": "thinking", "simple_smile": "slightly_smiling_face", "grinning_face_with_star_eyes": "star_struck",
    "face_with_rolling_eyes": "roll_eyes", "hugging_face": "hugs", "party_popper": "tada",
    "rolling_on_the_floor_laughing": "rofl", "face_palm": "facepalm", "man-shrugging": "man_shrugging",
    "woman-shrugging": "woman_shrugging", "white_frowning_face": "frowning_face", "robot_face": "robot",
    "heavy_heart_exclamation_mark_ornament": "heavy_heart_exclamation", "the_horns": "metal",
    "sign_of_the_horns": "metal", "spock-hand": "vulcan_salute", "lower_left_ballpoint_pen": "pen",
    "man-facepalming": "man_facepalming", "woman-facepalming": "woman_facepalming", "thumbsup": "+1",
    "thumbsdown": "-1", "male-technologist": "man_technologist", "female-technologist": "woman_technologist",
    "squirrel": "chipmunk", "slightly_smiling": "slightly_smiling_face",
}

def main(src, out):
    db = json.load(open(src))
    by = {}
    tones = set()
    for e in db:
        for a in e["aliases"]:
            by.setdefault(a, e["emoji"])
            if e.get("skin_tones"): tones.add(a)
    for slack, gem in SLACK.items():
        if gem in by: by.setdefault(slack, by[gem])
        if gem in tones: tones.add(slack)
    for k, v in by.items():
        assert "\t" not in k and "\n" not in k and '"""#' not in v, k
    lines = "\n".join(f"{k}\t{v}" for k, v in sorted(by.items()))
    with open(out, "w") as f:
        f.write("// Generated by dev/gen-emoji.py from gemoji + Slack aliases. Don't edit.\n")
        f.write("enum EmojiTable {\n")
        f.write('    static let pairs = #"""\n' + lines + '\n"""#\n')
        f.write('    static let skinTones = #"""\n' + "\n".join(sorted(tones)) + '\n"""#\n')
        f.write("}\n")
    print(f"{len(by)} names, {len(tones)} with skin tones -> {out}")

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(sys.argv[1], os.path.join(root, "Sources/RelayCore/Render/EmojiTable.swift"))
